### ISSUE TITLE
Erik Meijer's "Functional Programming Fundamentals" series source

### ISSUE THREAD

**Issue by jrgarcia** [caiorss/Functional-Programming#13]
You should probably link to the original source in `README.md`. All 13 videos can be found [here](http://channel9.msdn.com/Series/C9-Lectures-Erik-Meijer-Functional-Programming-Fundamentals). I didn't create a pull request because I wasn't sure whether you would rather link to the series or each individual video.

**Comment by caiorss** [comment]
Thank you very much for your suggestion. I updated the README.md.
