### ISSUE TITLE
typos 

### ISSUE THREAD

**Issue by princejwesley** [caiorss/Functional-Programming#6]
Some typos:

Pure Functions / **Referencail** Transparency / No side effect
**Clousure** - Returning functions from functions
Data **Imutability**

Lazy Evaluation ( **Dealayed** evaluation) by default
Data **Imutability**/ Haskell has no variables
Composability, one **fuction** can be connected to another.

**puryfing** an impure Language
Python uses eager **eavaluation** by default.
...

**Comment by thethomaseffect** [comment]
Why not create a pull request fixing these since you can fix them from the browser after making a fork? :)

**Comment by princejwesley** [comment]
Sure, I do. :+1:

**Comment by princejwesley** [comment]
[PR](https://github.com/caiorss/Functional-Programming/pull/8) for this issue.

**Comment by caiorss** [comment]
Fixed.
